name: Build Linux Packages
on:
  push:
    branches:
      - main

env:
  DIST: el9
  ARCH: noarch
  PKG_NAME: testrpm   # Define the package name here

jobs:
  build_tarball:
    name: Build source archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace version in RPM spec so correct source is downloaded when building RPM
        run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{ github.ref_name }}/' ${{ env.PKG_NAME }}.spec

      - name: Create source archive
        run: tar -cvzf ${{ env.PKG_NAME }}-${{ github.ref_name }}.tar.gz *  # Create the tarball

      - name: Upload source archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PKG_NAME }}-${{ github.ref_name }}.tar.gz
          path: ${{ env.PKG_NAME }}-${{ github.ref_name }}.tar.gz

  build_rpm:
    name: Build .rpm package
    needs: build_tarball
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies for building RPMs
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Set up rpmbuild directories
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp ${{ env.PKG_NAME }}.spec ~/rpmbuild/SPECS/
          mv ${{ env.PKG_NAME }}-${{ github.ref_name }}.tar.gz ~/rpmbuild/SOURCES/${{ env.PKG_NAME }}-main.tar.gz  # Rename and move tarball

      - name: Build the RPM package
        run: rpmbuild -ba ~/rpmbuild/SPECS/${{ env.PKG_NAME }}.spec

      - name: Upload .rpm package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PKG_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
          path: ~/rpmbuild/RPMS/noarch/*.rpm

