name: Build Linux Packages
on:
  push:
    branches:
      - main

env:
  DIST: el9
  ARCH: noarch
  PKG_NAME: testrpm   # Define the package name here

jobs:
  build_tarball:
    name: Build source archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace version in RPM spec so correct source is downloaded when building RPM
        run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{ github.ref_name }}/' ${{ env.PKG_NAME }}.spec

      - name: Create source archive
        run: tar -cvf ${{ env.PKG_NAME }}-${{ github.ref_name }}.tar.gz *

      - name: Upload source archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PKG_NAME }}-${{ github.ref_name }}.tar.gz
          path: ${{ env.PKG_NAME }}-${{ github.ref_name }}.tar.gz

  build_rpm:
    name: Build .rpm package
    needs: build_tarball
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace version in RPM spec so correct source is downloaded when building RPM
        run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{ github.ref_name }}/' ${{ env.PKG_NAME }}.spec


      - name: Run rpmbuild on RPM spec to produce package
        id: rpm
        uses: jiro4989/build-rpm-action@v2
        with:
          package: ${{ env.PKG_NAME }}    # Set package name here instead of spec_file
          package_root: '.'               # Set the root directory for the package
          version: ${{ github.ref_name }}  # Set the version based on the current Git ref
          arch: ${{ env.ARCH }}            # Set the architecture (noarch in your case)
          maintainer: 'Your Name'          # Set the maintainer
          vendor: 'Your Vendor Name'       # Set the vendor
          desc: 'Ansible playbook to add text to a file'  # Use 'desc' instead of 'description'
          license: 'GPL'

      # - name: Run rpmbuild on RPM spec to produce package
      #   id: rpm
      #   uses: jiro4989/build-rpm-action@v2
      #   with:
      #     spec_file: ${{ env.PKG_NAME }}.spec
      #     package_root: '.'  # Set the root directory for the package
      #     version: ${{ github.ref_name }}  # Set the version based on the current Git ref
      #     arch: ${{ env.ARCH }}            # Set the architecture (noarch in your case)
      #     maintainer: 'Your Name'          # Set the maintainer
      #     vendor: 'Your Vendor Name'       # Set the vendor
      #     description: 'Ansible playbook to add text to a file'  # Set a description
      #     license: 'GPL'                   # Set the license

      - name: Upload .rpm package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PKG_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
          path: rpmbuild/RPMS/${{ env.ARCH }}/*.rpm

